### ISSUE TITLE
Certificate renewal will only work if webserver is not running!

### ISSUE THREAD

**Issue by NickJH** [WikiSuite/app-lets-encrypt#11]
There has been a change to the /usr/clearos/apps/lets_encrypt/deploy/renew script and the RESULT line now includes the switch "--standalone". This means certbot will use its built-in webserver which is great if you have not set up and started a webserver. If you already have a running web server, this command will always fail as it cannot bind to port 80. It is, however, a great solution if you are not running a webserver.

I believe the certificate creation and renewal routines should be made to detect if the web server is running (or if anything is bound to port 80). If it is not it should use the --standalone switch. Otherwise it should not.

This is a pretty urgent issue as the last update appeared around 12th Feb (which may have been the one containing the change) so we are approaching the 30 day limit where existing certificates will begin to expire.

**Comment by pcbaldwin** [comment]
This was resolved with a series of commits on February 21. 

- The first build attempt failed: http://koji.clearos.com/koji/taskinfo?taskID=15671
- A subsequent March 2 rebuild failed: http://koji.clearos.com/koji/taskinfo?taskID=15773

I'll try again this week.  Since it's urgent, I'll manually build the RPM and push it through the 3rd party repo system if the buildsys is misbehaving.

**Comment by pcbaldwin** [comment]
Success!  I'll verify the update and if all goes well it will go out on Wednesday.
