### ISSUE TITLE
Let's Encrypt app fails when creating certificate for multiple domains on one certificate

### ISSUE THREAD

**Issue by NickJH** [WikiSuite/app-lets-encrypt#5]
If you try to create a certificate, say for a Primary Domain imap.my_domain.com and put smtp.my_domain.com in the Other Domains box, the Webconfig fails throwing a warning:

Warning
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for imap.howitts.co.uk
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.

Creating the certificate without any "Other Domains" works.

This looks like it is fallout from the TLS-SNI-01 challenge for Let's Encrypt being shut down for the moment because of security concerns. An updated version of certbot is being developed to mitigate the issue: https://community.letsencrypt.org/t/help-test-certbot-apache-and-nginx-fixes-for-tls-sni-01-outage/50207/32 but I think the issue should be tracked until the new certbot package becomes available in ClearOS.

**Comment by marclaporte** [comment]
@NickJH: Thank you for this detailed report, and the workaround.

**Comment by NickJH** [comment]
@marclaporte: 
[https://community.letsencrypt.org/t/certbot-0-21-0-release/50725](url) Certbot 0.21.0 was released a week ago but has not made it to epel-testing or epel which is the source for ClearOS. Do you know how to get it into the epel loop?

**Comment by pcbaldwin** [comment]
The upgrade to 0.21.0 is more complicated than anticipated.  Certbot moved to a 3rd party JOSE (JavaScript Object Signing and Encryption) library.  Here's the commit:

https://github.com/certbot/certbot/commit/2abc94661a16f1a4c5bc18e9c48870f2db458eac#diff-53bce4f1dfa0fe8e7ca126f91b35d3a6

That means a new **python-jose** RPM needs to be created in order to support certbot 0.21.0.  Usually, an upgrade is a matter forking the upstream git repository, changing the version numbers and  quickly rebuilding the package.  Occasionally, some re-patching is required, but it's usually straightforward.  This upgrade actually requires a new python-jose RPM and spec file!

It will take an hour or two to get this all done and tested.  Perhaps it would be better to ping EPEL?

**Comment by NickJH** [comment]
If I read this right, RedHat may have started running with it:
https://bugzilla.redhat.com/show_bug.cgi?id=1537805
https://bugzilla.redhat.com/show_bug.cgi?id=1535990

**Comment by pcbaldwin** [comment]
Nice find Nick.  Yes, it looks like the EPEL maintainer is on it.

**Comment by pcbaldwin** [comment]
Certbot has been updated to 0.21.0.
